version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    networks:
      - app_network

  redis:
    image: redis:latest
    container_name: redis_cache
    ports:
      - "6379:6379"
    restart: always
    networks:
      - app_network

  smtp:
    image: rnwood/smtp4dev
    container_name: smtp4dev
    ports:
      - "8025:80"    # رابط کاربری وب
      - "2525:25"    # پورت SMTP
    restart: always
    networks:
      - app_network

volumes:
  postgres_data:
  redis_data:

networks:
  app_network:
