services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-default_user}       
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-default_password} 
      POSTGRES_DB: ${POSTGRES_DB:-default_db}              
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    networks:
      - app_network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always
    networks:
      - app_network

  smtp4dev:
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      - '5000:80'
      - '25:25'
      - '143:143'
    volumes:
      - smtp4dev-data:/smtp4dev
    environment:
      - ServerOptions__Urls=http://*:80
      - ServerOptions__HostName=smtp4dev
    networks:
      - app_network 

  backend:
    container_name: backend
    build: .
    environment:
      - EMAIL_HOST=${EMAIL_HOST:-smtp4dev}      # مقدار پیش‌فرض: smtp4dev
      - EMAIL_PORT=${EMAIL_PORT:-25}            # مقدار پیش‌فرض: 25
    env_file:
      - .env
    command: ["/wait-for-it.sh", "db:5432", "--", "python", "manage.py", "runserver", "0.0.0.0:8000"]
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    restart: always
    networks:
      - app_network
    volumes:
      - .:/app

volumes:
  postgres_data:
  smtp4dev-data:

networks:
  app_network:
