name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Clone the repository
    - name: Checkout Code
      uses: actions/checkout@v4

    # Set up Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build and start services
    - name: Build and Start Docker Services
      run: docker-compose up -d --build

    # Wait for database and backend to be ready
    - name: Wait for Backend and Database to be Ready
      run: |
        sleep 10
        docker-compose exec backend python manage.py migrate
        docker-compose exec backend python manage.py collectstatic --noinput

    # Run Tests
    - name: Run Tests
      run: docker-compose exec backend pytest .

    # Cleanup Docker containers
    - name: Stop Docker Services
      run: docker-compose down
