name: Run Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Clone the repository
    - name: Checkout Code
      uses: actions/checkout@v4

    # Step 2: Install Docker Compose
    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose-plugin

    # Step 3: Build and Start Docker Services
    - name: Build and Start Docker Services
      run: docker compose up -d --build

    # Step 4: Wait for Services to Start
    - name: Wait for Services to Start
      run: sleep 10

    # Step 5: Run Tests
    - name: Run Tests
      run: docker compose exec backend pytest .

    # Step 6: Cleanup Docker containers
    - name: Stop Docker Services
      run: docker compose down
