name: Run Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Clone the repository
    - name: Checkout Code
      uses: actions/checkout@v4

    # Build and start services
    - name: Build and Start Docker Services
      run: docker-compose up -d --build

    # Wait for backend and database to be ready
    - name: Wait for Services to Start
      run: sleep 10

    # Run Tests
    - name: Run Tests
      run: docker-compose exec backend pytest .

    # Cleanup Docker containers
    - name: Stop Docker Services
      run: docker-compose down
