name: CI for LinkShortener

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      # Verify Docker Compose installation
      - name: Verify Docker Compose
        run: docker-compose version

      # Build and run services
      - name: Build and start services
        run: docker-compose up -d

      # Run tests inside the backend service
      - name: Run tests
        run: docker-compose exec backend pytest .
